
import { Translations, Market, LocationData, MarketStats, NewsArticle } from './types';

export const TRANSLATIONS: Record<string, Translations> = {
  VN: {
    motto: "Không bán nhà. Không dạy làm giàu nhanh. Chỉ giúp bạn nhìn rõ thị trường.",
    headerTitle: "Hiểu thị trường. Định hướng hành động.",
    headerSubtitle: "BDS Navigator – La bàn cho nhà đầu tư.",
    heroTitle: "Thị trường BĐS hôm nay – cập nhật nhanh",
    heroSubtitle: "Xem giá thực tế và tình hình cho thuê tại khu vực",
    marketStatus: "Giá nhà ổn định, tỉ lệ trống tăng nhẹ",
    selectMarket: "Quốc Gia",
    selectCity: "Thành Phố",
    selectDistrict: "Quận / Huyện",
    priceIndex: "Chỉ số giá thực tế khu vực",
    rentOccupancy: "Tỷ lệ thuê trung bình & giá thuê",
    investorBriefing: "Bản tin nhanh 90s cho nhà đầu tư",
    trendsNews: "Xu hướng & Yếu tố tác động",
    freeTools: "Công cụ miễn phí",
    householdCalc: "Máy tính ngân sách",
    financingCalc: "Tính toán tài chính",
    excelDownload: "Tải về Excel",
    privacyNotice: "Tất cả dữ liệu được xử lý cục bộ, không lưu trữ",
    goalsTitle: "BẠN ĐÃ CÓ MỤC TIÊU ĐẦU TƯ CHƯA?",
    goalsSubtitle: "Nếu bạn muốn, chúng tôi sẽ lọc thông tin phù hợp hơn cho bạn.",
    goalOptions: ["GIA ĐÌNH & NHÀ Ở", "THU NHẬP THỤ ĐỘNG", "KINH DOANH BĐS TOÀN THỜI GIAN", "TĂNG GIÁ TRỊ TÀI SẢN"],
    horizonTitle: "Tầm nhìn đầu tư:",
    saveContinue: "LƯU & TIẾP TỤC",
    skip: "TIẾP TỤC MÀ KHÔNG CẦN LƯU",
    stable: "Giá tốt",
    risk: "Rủi ro",
    avgBuy: "Giá mua trung bình",
    avgRent: "Giá thuê trung bình",
    apartment: "Căn hộ",
    house: "Nhà thổ cư",
    land: "Đất nền",
    all: "Tất cả",
    tradingActive: "GIAO DỊCH SÔI ĐỘNG",
    highYield: "TIỀM NĂNG CAO",
    newPlanning: "QUY HOẠCH MỚI",
    brandingSub: "Thấu hiểu thị trường BĐS",
    realPrice: "Chỉ số giá thực tế khu vực",
    cashflow: "Dòng tiền",
    riskLevel: "Rủi ro",
    property: "Bất động sản",
    askingPrice: "Giá Chào Bán",
    usage: "Tình Trạng",
    recommendation: "Khuyến Nghị",
    newsToday: "Bản Tin Đầu Tư Ngày Hôm Nay",
    podcast: "Podcast Tư Vấn Đầu Tư",
    watchVideo: "Xem Video",
    medium: "Trung Bình",
    high: "Cao",
    low: "Thấp",
    memberLogin: "Đăng nhập",
    alreadyMember: "Đã có tài khoản?",
    shophouse: "Nhà phố thương mại",
    industry: "BĐS Công nghiệp",
    libraryTitle: "Thư viện & Ebook",
    librarySubtitle: "Tài liệu sưu tầm cho nhà đầu tư",
    downloadFree: "Tải Miễn Phí",
    catLegal: "Pháp lý & Thuế",
    catInfra: "Hạ tầng & Quy hoạch",
    catInterest: "Lãi suất & Ngân hàng",
    catPolitics: "Chính trị & Chính sách",
    catSocio: "Dân cư & Thu nhập",
    newsDisclaimer: "Tin tức được tổng hợp tự động từ các nguồn RSS công khai nhằm mục đích tham khảo. Bản quyền nội dung thuộc về các đơn vị phát hành gốc."
  },
  DE: {
    motto: "Wir verkaufen keine Häuser. Wir lehren nicht, wie man schnell reich wird. Wir helfen Ihnen nur, den Markt klar zu sehen.",
    headerTitle: "Markt verstehen. Richtig handeln.",
    headerSubtitle: "BDS Navigator – Kompass für Immobilieninvestoren.",
    heroTitle: "Immobilienmarkt heute – schnelle Übersicht",
    heroSubtitle: "Sehen Sie aktuelle Preise & Mietlage Ihrer Region",
    marketStatus: "Preise stabil, Leerstand leicht gestiegen",
    selectMarket: "Land",
    selectCity: "Stadt",
    selectDistrict: "Bezirk",
    priceIndex: "Regionaler Realpreis-Index",
    rentOccupancy: "Durchschnittliche Mietquote & Mietpreise",
    investorBriefing: "90-Sekunden-News für Investoren",
    trendsNews: "Trends & Marktfaktoren",
    freeTools: "Kostenlose Tools",
    householdCalc: "Haushaltsrechner",
    financingCalc: "Finanzierungsrechner",
    excelDownload: "Excel Download",
    privacyNotice: "Alle Daten lokal, keine Speicherung",
    goalsTitle: "HABEN SIE SCHON KONKRETE ZIELE?",
    goalsSubtitle: "Ziele angeben für personalisierte Hinweise.",
    goalOptions: ["FAMILIE & WOHNEN", "PASSIVES EINKOMMEN", "VOLLZEIT-IMMOBILIEN", "ASSET-WACHSTUM"],
    horizonTitle: "Zeithorizont:",
    saveContinue: "SPEICHERN & WEITER",
    skip: "WEITER OHNE SPEICHERN",
    stable: "Stabil",
    risk: "Risiko",
    avgBuy: "Durchschnittlicher Kaufpreis",
    avgRent: "Durchschnittliche Miete",
    apartment: "Wohnung",
    house: "Haus",
    land: "Grundstück",
    all: "Alle",
    tradingActive: "AKTIVER HANDEL",
    highYield: "HOHES POTENZIAL",
    newPlanning: "NEUE PLANUNG",
    brandingSub: "Immobilienmarkt verstehen",
    realPrice: "Realpreis-Index",
    cashflow: "Cashflow",
    riskLevel: "Risiko",
    property: "Objekt",
    askingPrice: "Angebotspreis",
    usage: "Nutzung",
    recommendation: "Empfehlung",
    newsToday: "Investoren-News Aktuell",
    podcast: "Investment Podcast",
    watchVideo: "Video Ansehen",
    medium: "Mittel",
    high: "Hoch",
    low: "Niedrig",
    memberLogin: "Einloggen",
    alreadyMember: "Bereits Mitglied?",
    shophouse: "Gewerbehaus",
    industry: "Industrieimmobilien",
    libraryTitle: "Bibliothek & Ebook",
    librarySubtitle: "Gesammelte Werke für Investoren",
    downloadFree: "Kostenlos",
    catLegal: "Gesetze & Steuern",
    catInfra: "Infrastruktur",
    catInterest: "Zinsen & Banken",
    catPolitics: "Politik",
    catSocio: "Einkommen & Demografie",
    newsDisclaimer: "Nachrichten werden automatisch aus öffentlichen RSS-Quellen zu Informationszwecken aggregiert. Das Urheberrecht liegt bei den ursprünglichen Herausgebern."
  },
  EN: {
    motto: "No selling houses. No get-rich-quick teaching. Just helping you see the market clearly.",
    headerTitle: "Understand the market. Orient action.",
    headerSubtitle: "BDS Navigator – Compass for investors.",
    heroTitle: "Real Estate Market Today – Quick Overview",
    heroSubtitle: "View real prices & rental status in your area",
    marketStatus: "Prices stable, vacancy slightly up",
    selectMarket: "Country",
    selectCity: "City",
    selectDistrict: "District",
    priceIndex: "Regional Real Price Index",
    rentOccupancy: "Average occupancy & rent prices",
    investorBriefing: "90-sec investor briefing",
    trendsNews: "Trends & Key Factors",
    freeTools: "Free Tools",
    householdCalc: "Budget Calculator",
    financingCalc: "Financing Calculator",
    excelDownload: "Excel Download",
    privacyNotice: "All data processed locally, not stored",
    goalsTitle: "DO YOU HAVE INVESTMENT GOALS?",
    goalsSubtitle: "Enter goals to receive personalized guidance.",
    goalOptions: ["FAMILIE & WOHNEN", "PASSIVES EINKOMMEN", "FULL-TIME REAL ESTATE", "ASSET GROWTH"],
    horizonTitle: "Time Horizon:",
    saveContinue: "SAVE & CONTINUE",
    skip: "CONTINUE WITHOUT SAVING",
    stable: "Good Deal",
    risk: "Risk",
    avgBuy: "Avg. Purchase Price",
    avgRent: "Avg. Rental Price",
    apartment: "Apartment",
    house: "House",
    land: "Land",
    all: "All",
    tradingActive: "TRADING ACTIVE",
    highYield: "HIGH YIELD POT.",
    newPlanning: "NEW PLANNING",
    brandingSub: "Real Estate Understanding",
    realPrice: "Real Price Index",
    cashflow: "Cashflow",
    riskLevel: "Risk",
    property: "Property",
    askingPrice: "Asking Price",
    usage: "Status",
    recommendation: "Recommendation",
    newsToday: "Investor News Today",
    podcast: "Investment Podcast",
    watchVideo: "Watch Video",
    medium: "Medium",
    high: "High",
    low: "Low",
    memberLogin: "Login",
    alreadyMember: "Already a member?",
    shophouse: "Shophouse",
    industry: "Industrial RE",
    libraryTitle: "Library & Ebooks",
    librarySubtitle: "Collected resources for investors",
    downloadFree: "Free Download",
    catLegal: "Legal & Tax",
    catInfra: "Infrastructure",
    catInterest: "Interest & Banks",
    catPolitics: "Politics",
    catSocio: "Demographics",
    newsDisclaimer: "News is automatically aggregated from public RSS sources for informational purposes. Copyright belongs to the original publishers."
  }
};

export const MARKET_DATA: Record<Market, LocationData> = {
  VN: {
    cities: [
      "Hà Nội", "Hồ Chí Minh", "Đà Nẵng", "Hội An", "Bình Dương", "Đồng Nai", 
      "Quảng Ninh", "Hải Phòng", "Cần Thơ", "Nha Trang", "Vũng Tàu", 
      "Huế", "Vinh", "Đà Lạt", "Bắc Ninh", "Thanh Hóa",
      "Hưng Yên", "Vĩnh Phúc", "Thái Nguyên", "Hải Dương", "Nam Định",
      "Thái Bình", "Hà Nam", "Ninh Bình", "Quy Nhơn", "Buôn Ma Thuột",
      "Phú Quốc", "Long An", "Tiền Giang", "Sapa", "Phan Thiết"
    ],
    districts: {
      "Hà Nội": [
        "Đông Anh", "Thường Tín", "Cầu Giấy", "Nam Từ Liêm", "Bắc Từ Liêm", "Long Biên", 
        "Hoàn Kiếm", "Tây Hồ", "Hoàng Mai", "Ba Đình", "Đống Đa", "Thanh Xuân", 
        "Hà Đông", "Gia Lâm", "Sóc Sơn", "Mê Linh", "Hoài Đức", "Thanh Trì",
        "Đan Phượng", "Phú Xuyên", "Phúc Thọ", "Quốc Oai", "Thạch Thất", 
        "Chương Mỹ", "Thanh Oai", "Ứng Hòa", "Mỹ Đức", "Ba Vì", "Sơn Tây"
      ],
      "Hồ Chí Minh": [
        "Quận 1", "Quận 3", "Quận 4", "Quận 5", "Quận 6", "Quận 7", "Quận 8", 
        "Quận 10", "Quận 11", "Quận 12", "Thủ Đức", "Bình Thạnh", "Gò Vấp", 
        "Phú Nhuận", "Tân Bình", "Tân Phú", "Bình Tân", "Hóc Môn", "Củ Chi", 
        "Nhà Bè", "Bình Chánh", "Cần Giờ"
      ],
      "Đà Nẵng": ["Hải Châu", "Ngũ Hành Sơn", "Sơn Trà", "Liên Chiểu", "Thanh Khê", "Cẩm Lệ", "Hòa Vang", "Hoàng Sa"],
      "Hội An": ["Minh An", "Sơn Phong", "Cẩm Phô", "Tân An", "Thanh Hà", "Cẩm Châu", "Cẩm An", "Cửa Đại"],
      "Bình Dương": ["Thuận An", "Dĩ An", "Thủ Dầu Một", "Bến Cát", "Tân Uyên", "Bàu Bàng", "Bắc Tân Uyên", "Dầu Tiếng", "Phú Giáo"],
      "Đồng Nai": ["Biên Hòa", "Long Thành", "Nhơn Trạch", "Trảng Bom", "Vĩnh Cửu", "Thống Nhất", "Long Khánh", "Xuân Lộc"],
      "Quảng Ninh": ["Hạ Long", "Móng Cái", "Cẩm Phả", "Uông Bí", "Vân Đồn", "Quảng Yên", "Đông Triều", "Tiên Yên"],
      "Hải Phòng": ["Lê Chân", "Ngô Quyền", "Hồng Bàng", "Thủy Nguyên", "Hải An", "Kiến An", "Đồ Sơn", "Dương Kinh", "An Dương"],
      "Cần Thơ": ["Ninh Kiều", "Cái Răng", "Bình Thủy", "Thốt Nốt", "Ô Môn", "Phong Điền", "Cờ Đỏ"],
      "Nha Trang": ["Lộc Thọ", "Phước Tiến", "Vĩnh Nguyên", "Vĩnh Hải", "Phước Long", "Vĩnh Phước", "Vĩnh Thọ"],
      "Vũng Tàu": ["Phường 1", "Phường 2", "Thắng Tam", "Nguyễn An Ninh", "Rạch Dừa", "Phường 8", "Phường 9"],
      "Huế": ["Vĩnh Ninh", "Phú Nhuận", "Xuân Phú", "Vỹ Dạ", "Phước Vĩnh", "Trường An"],
      "Vinh": ["Hưng Bình", "Lê Mao", "Trường Thi", "Hà Huy Tập", "Quán Bàu", "Hưng Dũng"],
      "Đà Lạt": ["Phường 1", "Phường 2", "Phường 8", "Phường 10", "Phường 4", "Phường 3"],
      "Bắc Ninh": ["Tiền An", "Ninh Xá", "Suối Hoa", "Đại Phúc", "Võ Cường", "Vệ An", "Yên Phong", "Quế Võ"],
      "Thanh Hóa": ["Đông Thọ", "Điện Biên", "Lam Sơn", "Ba Đình", "Ngọc Trạo", "Sầm Sơn"],
      "Hưng Yên": ["Văn Giang", "Văn Lâm", "Mỹ Hào", "TP Hưng Yên", "Khoái Châu", "Yên Mỹ"],
      "Vĩnh Phúc": ["Vĩnh Yên", "Phúc Yên", "Bình Xuyên", "Vĩnh Tường", "Tam Đảo"],
      "Thái Nguyên": ["TP Thái Nguyên", "Sông Công", "Phổ Yên", "Phú Bình", "Đại Từ"],
      "Hải Dương": ["TP Hải Dương", "Chí Linh", "Kinh Môn", "Cẩm Giàng", "Nam Sách"],
      "Nam Định": ["TP Nam Định", "Mỹ Lộc", "Vụ Bản", "Nam Trực", "Giao Thủy"],
      "Thái Bình": ["TP Thái Bình", "Đông Hưng", "Hưng Hà", "Tiền Hải", "Thái Thụy"],
      "Hà Nam": ["Phủ Lý", "Duy Tiên", "Kim Bảng", "Lý Nhân", "Thanh Liêm"],
      "Ninh Bình": ["TP Ninh Bình", "Tam Điệp", "Hoa Lư", "Gia Viễn", "Yên Khánh"],
      "Quy Nhơn": ["Lê Hồng Phong", "Trần Phú", "Lý Thường Kiệt", "Nguyễn Văn Cừ", "Ghềnh Ráng"],
      "Buôn Ma Thuột": ["Tân Lợi", "Thắng Lợi", "Thống Nhất", "Tân An", "Tự An"],
      "Phú Quốc": ["Dương Đông", "An Thới", "Cửa Dương", "Cửa Cạn"],
      "Long An": ["Tân An", "Bến Lức", "Đức Hòa", "Cần Giuộc", "Cần Đước", "Kiến Tường"],
      "Tiền Giang": ["Mỹ Tho", "Cai Lậy", "Gò Công", "Châu Thành", "Cái Bè"],
      "Sapa": ["TT Sapa", "Tả Van", "Lao Chải", "Bản Hồ"],
      "Phan Thiết": ["Mũi Né", "Phú Hài", "Hàm Tiến", "Đức Nghĩa", "Hưng Long"]
    },
    news: [
      {
        id: 'vn-1',
        title: "Lãi suất ngân hàng hạ nhiệt, tín hiệu tích cực cho người mua nhà",
        summary: "Nhiều ngân hàng thương mại lớn tại Việt Nam vừa thông báo giảm lãi suất cho vay mua nhà.",
        content: "Thị trường bất động sản Việt Nam đang đón nhận những tín hiệu tích cực khi hàng loạt ngân hàng thương mại lớn công bố các gói tín dụng ưu đãi với mức lãi suất giảm từ 0.5% đến 1.5% so với kỳ trước. Điều này được kỳ vọng sẽ kích cầu tiêu dùng và giải tỏa áp lực tài chính cho người mua nhà ở thực. Các chuyên gia dự báo thanh khoản thị trường sẽ cải thiện rõ rệt trong quý tới.",
        imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80",
        sourceUrl: "https://vneconomy.vn",
        date: "Hôm nay, 08:30",
        category: 'INTEREST_BANKS'
      },
      {
        id: 'vn-2',
        title: "Quy hoạch phân khu đô thị sông Hồng: Cơ hội bứt phá cho Đông Anh",
        summary: "Dự án quy hoạch đô thị ven sông Hồng hứa hẹn mang lại diện mạo mới cho khu vực phía Bắc thủ đô.",
        content: "Với việc chính thức phê duyệt đồ án quy hoạch phân khu đô thị sông Hồng, huyện Đông Anh đang đứng trước cơ hội trở thành một trong những trung tâm kinh tế - văn hóa mới của Hà Nội. Sự đầu tư mạnh mẽ vào hạ tầng giao thông và các khu đô thị sinh thái đang khiến giá đất tại đây có xu hướng tăng ổn định, thu hút sự quan tâm của nhiều nhà đầu tư dài hạn.",
        imageUrl: "https://images.unsplash.com/photo-1449156059586-7620afaf334e?auto=format&fit=crop&w=800&q=80",
        sourceUrl: "https://hanoi.gov.vn",
        date: "Hôm qua, 15:45",
        category: 'INFRASTRUCTURE'
      },
      {
        id: 'vn-3',
        title: "Giá thuê căn hộ chung cư tại TP.HCM duy trì đà tăng nhẹ",
        summary: "Nhu cầu thuê nhà tại các quận trung tâm vẫn ở mức cao do lực lượng lao động trẻ quay trở lại thành phố.",
        content: "Theo dữ liệu thị trường mới nhất, giá thuê căn hộ chung cư tại Quận 1, Quận 3 và Quận 7 vẫn giữ vững phong độ với mức tăng từ 3-5%. Nguyên nhân chủ yếu do nguồn cung căn hộ mới hạn chế trong khi nhu cầu từ các chuyên gia nước ngoài và người lao động có thu nhập cao không ngừng gia tăng. Tỷ lệ lấp đầy tại các tòa nhà cao cấp đạt trên 85%.",
        imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80",
        sourceUrl: "https://cafef.vn",
        date: "Hôm qua, 10:20",
        category: 'SOCIO_ECONOMIC'
      }
    ]
  },
  DE: {
    cities: [
      "Berlin", "München", "Hamburg", "Frankfurt", "Köln", 
      "Düsseldorf", "Leipzig", "Stuttgart", "Dortmund", "Essen", 
      "Bremen", "Dresden", "Hannover", "Nürnberg", "Duisburg",
      "Bochum", "Wuppertal", "Bielefeld", "Bonn", "Münster",
      "Karlsruhe", "Mannheim", "Augsburg", "Wiesbaden", "Gelsenkirchen",
      "Mönchengladbach", "Braunschweig", "Chemnitz", "Kiel", "Aachen",
      "Freiburg", "Heidelberg", "Potsdam", "Mainz", "Rostock", "Erfurt", "Saarbrücken"
    ],
    districts: {
      "Berlin": ["Mitte", "Pankow", "Neukölln", "Charlottenburg", "Spandau", "Steglitz", "Reinickendorf", "Friedrichshain-Kreuzberg", "Tempelhof-Schöneberg", "Lichtenberg", "Marzahn-Hellersdorf", "Treptow-Köpenick"],
      "München": ["Altstadt", "Schwabing", "Sendling", "Bogenhausen", "Neuhausen", "Pasing", "Maxvorstadt", "Ludwigsvorstadt", "Haidhausen", "Nymphenburg", "Moosach", "Milbertshofen"],
      "Hamburg": ["Altona", "Eimsbüttel", "Harburg", "Bergedorf", "Wandsbek", "Mitte", "Nord"],
      "Frankfurt": ["Innenstadt", "Sachsenhausen", "Bornheim", "Westend", "Gallus", "Nordend", "Bockenheim", "Ostend", "Höchst", "Niederrad"],
      "Köln": ["Innenstadt", "Rodenkirchen", "Lindenthal", "Ehrenfeld", "Nippes", "Mülheim", "Porz", "Kalk", "Chorweiler"],
      "Düsseldorf": ["Altstadt", "Pempelfort", "Bilk", "Oberkassel", "Grafenberg", "Stadtmitte", "Flingern", "Benrath", "Kaiserswerth"],
      "Leipzig": ["Mitte", "Plagwitz", "Connewitz", "Gohlis", "Lindenau", "Südvorstadt", "Reudnitz"],
      "Stuttgart": ["Mitte", "Bad Cannstatt", "Vaihingen", "Zuffenhausen", "Degerloch", "West", "Süd", "Feuerbach"],
      "Dortmund": ["Mitte", "Hörde", "Hombruch", "Brackel", "Innenstadt-West", "Innenstadt-Ost", "Aplerbeck"],
      "Essen": ["Mitte", "Rüttenscheid", "Werden", "Kettwig", "Stadtkern", "Südviertel", "Altenessen"],
      "Bremen": ["Mitte", "Neustadt", "Schwachhausen", "Horn-Lehe", "Vahr", "Hemelingen"],
      "Dresden": ["Altstadt", "Neustadt", "Blasewitz", "Plauen", "Cotta", "Pieschen"],
      "Hannover": ["Mitte", "Südstadt", "List", "Linden", "Nordstadt", "Herrenhausen"],
      "Nürnberg": ["Mitte", "Südstadt", "Langwasser", "St. Johannis", "Gostenhof", "Mögeldorf"],
      "Duisburg": ["Mitte", "Hamborn", "Meiderich", "Rheinhausen", "Walsum", "Süd"],
      "Bochum": ["Mitte", "Wattenscheid", "Langendreer", "Weitmar", "Stiepel"],
      "Wuppertal": ["Elberfeld", "Barmen", "Vohwinkel", "Cronenberg", "Ronsdorf"],
      "Bielefeld": ["Mitte", "Brackwede", "Heepen", "Schildesche", "Senne"],
      "Bonn": ["Zentrum", "Bad Godesberg", "Beuel", "Hardtberg"],
      "Münster": ["Mitte", "Nord", "Ost", "West", "Süd-Ost", "Hiltrup"],
      "Karlsruhe": ["Innenstadt-Ost", "Innenstadt-West", "Südstadt", "Durlach", "Mühlburg"],
      "Mannheim": ["Innenstadt", "Neckarstadt", "Lindenhof", "Käfertal", "Sandhofen"],
      "Augsburg": ["Innenstadt", "Oberhausen", "Haunstetten", "Lechhausen", "Göggingen"],
      "Wiesbaden": ["Mitte", "Rheingauviertel", "Biebrich", "Dotzheim", "Bierstadt"],
      "Gelsenkirchen": ["Altstadt", "Buer", "Horst", "Erle", "Resse"],
      "Mönchengladbach": ["Mitte", "Rheydt", "Hardt", "Odenkirchen"],
      "Braunschweig": ["Mitte", "Östliches Ringgebiet", "Westliches Ringgebiet", "Nordstadt"],
      "Chemnitz": ["Zentrum", "Kaßberg", "Sonnenberg", "Schloßchemnitz"],
      "Kiel": ["Mitte", "Ravensberg", "Wik", "Gaarden"],
      "Aachen": ["Mitte", "Brand", "Eilendorf", "Haaren", "Kornelimünster"],
      "Freiburg": ["Mitte", "Herdern", "Wiehre", "Stühlinger", "Vauban"],
      "Heidelberg": ["Altstadt", "Bergheim", "Neuenheim", "Handschuhsheim", "Weststadt"],
      "Potsdam": ["Nördliche Innenstadt", "Südliche Innenstadt", "Babelsberg", "Bornstedt"],
      "Mainz": ["Altstadt", "Neustadt", "Oberstadt", "Gonsenheim"],
      "Rostock": ["Stadtmitte", "Kröpeliner-Tor-Vorstadt", "Warnemünde", "Reutershagen"],
      "Erfurt": ["Altstadt", "Andreasvorstadt", "Löbervorstadt", "Brühlervorstadt"],
      "Saarbrücken": ["Mitte", "St. Johann", "Malstatt", "Dudweiler"]
    },
    news: [
      {
        id: 'de-1',
        title: "Immobilienpreise in Berlin stabilisieren sich nach Korrekturphase",
        summary: "Nach den deutlichen Preisrückgängen der letzten Monate zeichnet sich am Berliner Markt ein Boden ab.",
        content: "Aktuelle Auswertungen von Marktanalysten zeigen, dass die Preise für Eigentumswohnungen in begehrten Lagen wie Mitte und Charlottenburg nicht weiter sinken. Käufer kehren langsam an den Markt zurück, getrieben durch die Erwartung stabilerer Zinsen. Besonders energieeffiziente Neubauten bleiben gefragt, während unsanierte Altbauten weiterhin Preisabschläge verzeichnen.",
        imageUrl: "https://images.unsplash.com/photo-1560520653-9e0e4c89eb11?auto=format&fit=crop&w=800&q=80",
        sourceUrl: "https://www.faz.net",
        date: "Heute, 09:15",
        category: 'INTEREST_BANKS'
      },
      {
        id: 'de-2',
        title: "Wohnungsnot in Großstädten: Neue Förderungen für den sozialen Wohnungsbau",
        summary: "Die Bundesregierung kündigt neue Milliardeninvestitionen an, um den Wohnungsbau anzukurbeln.",
        content: "Um dem akuten Wohnungsmangel in Metropolen wie München und Hamburg entgegenzuwirken, hat das Bauministerium ein neues Förderpaket geschnürt. Durch attraktive Tilgungszuschüsse und steuerliche Abschreibungsmöglichkeiten sollen private Investoren motiviert werden, verstärkt in preisgünstigen Wohnraum zu investieren. Experten begrüßen den Schritt, mahnen jedoch eine schnellere Digitalisierung der Baugenehmigungsprozesse an.",
        imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80",
        sourceUrl: "https://www.zeit.de",
        date: "Gestern, 17:00",
        category: 'POLITICS'
      },
      {
        id: 'de-3',
        title: "München bleibt teuerstes Pflaster, aber Renditen steigen",
        summary: "Trotz hoher Preise bieten Investitionen in der bayerischen Landeshauptstadt wieder bessere Chancen.",
        content: "Durch die gestiegenen Mieten bei gleichzeitig leicht gesunkenen Kaufpreisen haben sich die Mietrenditen in München auf einem Niveau von ca. 3,5% stabilisiert. Für Investoren, die auf langfristige Wertsteigerung setzen, bleibt München aufgrund der starken wirtschaftlichen Basis und des begrenzten Angebots der sicherste Hafen in Deutschland. Besonders im Umland steigen die Anfragen.",
        imageUrl: "https://images.unsplash.com/photo-1595841055318-400f939e8362?auto=format&fit=crop&w=800&q=80",
        sourceUrl: "https://www.sueddeutsche.de",
        date: "Gestern, 11:30",
        category: 'SOCIO_ECONOMIC'
      }
    ]
  }
};

export const CITY_STATS: Record<string, MarketStats> = {
  // VN Cities (Added Land & Shophouse mock data)
  "Hà Nội": { buyApt: "45-65", buyHouse: "120-250", buyLand: "60-120", buyShophouse: "200-400", rentApt: "12-18", rentHouse: "35-60", rentLand: "8-15", rentShophouse: "50-100" },
  "Hồ Chí Minh": { buyApt: "55-85", buyHouse: "150-350", buyLand: "80-200", buyShophouse: "250-500", rentApt: "15-25", rentHouse: "45-80", rentLand: "10-25", rentShophouse: "70-150" },
  "Đà Nẵng": { buyApt: "30-45", buyHouse: "80-150", buyLand: "40-90", buyShophouse: "120-220", rentApt: "8-12", rentHouse: "20-35", rentLand: "5-10", rentShophouse: "30-60" },
  "Hội An": { buyApt: "35-60", buyHouse: "90-250", buyLand: "50-120", buyShophouse: "150-300", rentApt: "8-15", rentHouse: "25-60", rentLand: "10-20", rentShophouse: "40-80" },
  "Bình Dương": { buyApt: "25-40", buyHouse: "50-120", buyLand: "30-70", buyShophouse: "80-160", rentApt: "6-10", rentHouse: "15-30", rentLand: "4-8", rentShophouse: "20-45" },
  "Đồng Nai": { buyApt: "20-35", buyHouse: "45-110", buyLand: "25-60", buyShophouse: "70-150", rentApt: "5-9", rentHouse: "12-25", rentLand: "3-7", rentShophouse: "18-40" },
  "Quảng Ninh": { buyApt: "28-45", buyHouse: "60-140", buyLand: "35-80", buyShophouse: "100-200", rentApt: "7-12", rentHouse: "15-35", rentLand: "5-10", rentShophouse: "25-50" },
  "Hải Phòng": { buyApt: "25-40", buyHouse: "55-130", buyLand: "30-75", buyShophouse: "90-180", rentApt: "6-10", rentHouse: "12-30", rentLand: "4-9", rentShophouse: "20-45" },
  "Cần Thơ": { buyApt: "22-35", buyHouse: "40-100", buyLand: "20-55", buyShophouse: "70-140", rentApt: "5-8", rentHouse: "10-20", rentLand: "3-6", rentShophouse: "15-35" },
  "Nha Trang": { buyApt: "35-60", buyHouse: "90-200", buyLand: "50-110", buyShophouse: "140-280", rentApt: "8-15", rentHouse: "25-50", rentLand: "8-18", rentShophouse: "35-70" },
  "Vũng Tàu": { buyApt: "30-50", buyHouse: "80-180", buyLand: "45-100", buyShophouse: "130-260", rentApt: "7-14", rentHouse: "20-45", rentLand: "6-12", rentShophouse: "30-65" },
  "Huế": { buyApt: "20-32", buyHouse: "45-90", buyLand: "25-55", buyShophouse: "70-130", rentApt: "5-8", rentHouse: "10-20", rentLand: "3-6", rentShophouse: "15-30" },
  "Vinh": { buyApt: "18-28", buyHouse: "40-85", buyLand: "20-50", buyShophouse: "65-120", rentApt: "4-7", rentHouse: "8-15", rentLand: "2-5", rentShophouse: "12-25" },
  "Đà Lạt": { buyApt: "35-55", buyHouse: "100-250", buyLand: "60-140", buyShophouse: "160-300", rentApt: "9-16", rentHouse: "25-55", rentLand: "8-15", rentShophouse: "40-80" },
  "Bắc Ninh": { buyApt: "22-35", buyHouse: "50-120", buyLand: "30-70", buyShophouse: "80-160", rentApt: "6-10", rentHouse: "15-30", rentLand: "4-8", rentShophouse: "20-45" },
  "Thanh Hóa": { buyApt: "18-28", buyHouse: "35-80", buyLand: "20-45", buyShophouse: "60-110", rentApt: "4-7", rentHouse: "8-15", rentLand: "2-5", rentShophouse: "12-25" },
  "Hưng Yên": { buyApt: "25-40", buyHouse: "60-130", buyLand: "35-75", buyShophouse: "90-170", rentApt: "6-10", rentHouse: "15-30", rentLand: "4-8", rentShophouse: "20-45" },
  "Vĩnh Phúc": { buyApt: "18-30", buyHouse: "40-90", buyLand: "22-50", buyShophouse: "65-130", rentApt: "5-8", rentHouse: "10-25", rentLand: "3-6", rentShophouse: "15-35" },
  "Thái Nguyên": { buyApt: "15-25", buyHouse: "35-80", buyLand: "18-45", buyShophouse: "55-110", rentApt: "4-7", rentHouse: "8-20", rentLand: "2-5", rentShophouse: "12-30" },
  "Hải Dương": { buyApt: "18-30", buyHouse: "40-90", buyLand: "22-50", buyShophouse: "65-130", rentApt: "5-8", rentHouse: "10-25", rentLand: "3-6", rentShophouse: "15-35" },
  "Nam Định": { buyApt: "16-28", buyHouse: "35-85", buyLand: "20-48", buyShophouse: "60-120", rentApt: "4-7", rentHouse: "8-20", rentLand: "2-5", rentShophouse: "12-30" },
  "Thái Bình": { buyApt: "16-28", buyHouse: "35-85", buyLand: "20-48", buyShophouse: "60-120", rentApt: "4-7", rentHouse: "8-20", rentLand: "2-5", rentShophouse: "12-30" },
  "Hà Nam": { buyApt: "15-25", buyHouse: "30-75", buyLand: "18-40", buyShophouse: "50-100", rentApt: "4-6", rentHouse: "7-18", rentLand: "2-5", rentShophouse: "10-25" },
  "Ninh Bình": { buyApt: "18-30", buyHouse: "40-90", buyLand: "22-50", buyShophouse: "65-130", rentApt: "5-8", rentHouse: "10-25", rentLand: "3-6", rentShophouse: "15-35" },
  "Quy Nhơn": { buyApt: "25-45", buyHouse: "60-150", buyLand: "35-85", buyShophouse: "100-200", rentApt: "7-12", rentHouse: "15-35", rentLand: "5-10", rentShophouse: "25-50" },
  "Buôn Ma Thuột": { buyApt: "18-30", buyHouse: "40-90", buyLand: "22-50", buyShophouse: "65-130", rentApt: "5-8", rentHouse: "10-25", rentLand: "3-6", rentShophouse: "15-35" },
  "Phú Quốc": { buyApt: "40-70", buyHouse: "100-300", buyLand: "80-250", buyShophouse: "200-500", rentApt: "10-20", rentHouse: "30-80", rentLand: "15-40", rentShophouse: "50-120" },
  "Long An": { buyApt: "18-30", buyHouse: "40-100", buyLand: "25-60", buyShophouse: "70-140", rentApt: "5-9", rentHouse: "12-25", rentLand: "3-7", rentShophouse: "18-40" },
  "Tiền Giang": { buyApt: "15-25", buyHouse: "35-80", buyLand: "20-45", buyShophouse: "60-110", rentApt: "4-7", rentHouse: "8-20", rentLand: "2-5", rentShophouse: "12-30" },
  "Sapa": { buyApt: "30-50", buyHouse: "80-200", buyLand: "50-120", buyShophouse: "140-280", rentApt: "8-15", rentHouse: "25-60", rentLand: "10-25", rentShophouse: "40-90" },
  "Phan Thiết": { buyApt: "25-45", buyHouse: "60-150", buyLand: "35-85", buyShophouse: "100-220", rentApt: "7-12", rentHouse: "15-40", rentLand: "5-12", rentShophouse: "25-60" },

  // DE Cities
  "Berlin": { buyApt: "5.5k-8k", buyHouse: "1.2M-2.5M", buyLand: "800k-1.5M", buyShophouse: "1.8M-3.5M", rentApt: "18-28", rentHouse: "2.5k-4.5k", rentLand: "1k-2k", rentShophouse: "3.5k-7k" },
  "München": { buyApt: "9k-14k", buyHouse: "2.5M-5M", buyLand: "1.5M-3M", buyShophouse: "3.5M-7M", rentApt: "22-35", rentHouse: "3.5k-6k", rentLand: "1.5k-3k", rentShophouse: "5k-10k" },
  "Hamburg": { buyApt: "6k-9k", buyHouse: "1.5M-3M", buyLand: "900k-1.8M", buyShophouse: "2M-4M", rentApt: "16-24", rentHouse: "2.8k-5k", rentLand: "1.2k-2.5k", rentShophouse: "4k-8k" },
  "Frankfurt": { buyApt: "7k-11k", buyHouse: "2M-4M", buyLand: "1.2M-2.2M", buyShophouse: "2.8M-5M", rentApt: "20-30", rentHouse: "3k-5.5k", rentLand: "1.5k-2.8k", rentShophouse: "4.5k-9k" },
  "Köln": { buyApt: "5k-7.5k", buyHouse: "1M-2M", buyLand: "600k-1.2M", buyShophouse: "1.5M-3M", rentApt: "14-22", rentHouse: "2k-4k", rentLand: "800-1.5k", rentShophouse: "3k-6k" },
  "Düsseldorf": { buyApt: "5.5k-8.5k", buyHouse: "1.2M-2.5M", buyLand: "700k-1.5M", buyShophouse: "1.8M-3.5M", rentApt: "16-25", rentHouse: "2.5k-4.5k", rentLand: "1k-2k", rentShophouse: "3.5k-7k" },
  "Leipzig": { buyApt: "3.5k-5.5k", buyHouse: "600k-1.2M", buyLand: "300k-600k", buyShophouse: "900k-1.8M", rentApt: "10-16", rentHouse: "1.5k-3k", rentLand: "500-1k", rentShophouse: "2k-4.5k" },
  "Stuttgart": { buyApt: "6k-9.5k", buyHouse: "1.5M-3.5M", buyLand: "900k-2M", buyShophouse: "2.2M-5M", rentApt: "18-26", rentHouse: "2.8k-5k", rentLand: "1.2k-2.5k", rentShophouse: "4k-8k" },
  "Dortmund": { buyApt: "2.5k-4k", buyHouse: "400k-800k", buyLand: "200k-400k", buyShophouse: "600k-1.2M", rentApt: "8-12", rentHouse: "1.2k-2.5k", rentLand: "400-800", rentShophouse: "1.8k-3.5k" },
  "Essen": { buyApt: "2.8k-4.5k", buyHouse: "500k-900k", buyLand: "250k-500k", buyShophouse: "750k-1.5M", rentApt: "9-13", rentHouse: "1.5k-2.8k", rentLand: "500-1k", rentShophouse: "2k-4k" },
  "Bremen": { buyApt: "3k-5k", buyHouse: "500k-1M", buyLand: "250k-550k", buyShophouse: "750k-1.5M", rentApt: "10-15", rentHouse: "1.5k-3k", rentLand: "500-1.2k", rentShophouse: "2k-4.5k" },
  "Dresden": { buyApt: "3.5k-5.5k", buyHouse: "600k-1.2M", buyLand: "300k-650k", buyShophouse: "900k-1.8M", rentApt: "10-15", rentHouse: "1.5k-3k", rentLand: "500-1.2k", rentShophouse: "2.2k-4.5k" },
  "Hannover": { buyApt: "3.8k-6k", buyHouse: "700k-1.4M", buyLand: "350k-750k", buyShophouse: "1M-2.2M", rentApt: "11-17", rentHouse: "1.8k-3.5k", rentLand: "600-1.5k", rentShophouse: "2.5k-5k" },
  "Nürnberg": { buyApt: "4.5k-7k", buyHouse: "800k-1.6M", buyLand: "400k-900k", buyShophouse: "1.2M-2.5M", rentApt: "13-19", rentHouse: "2k-3.8k", rentLand: "800-1.8k", rentShophouse: "3k-6k" },
  "Duisburg": { buyApt: "2k-3.5k", buyHouse: "300k-600k", buyLand: "150k-350k", buyShophouse: "450k-900k", rentApt: "7-11", rentHouse: "1k-2k", rentLand: "300-700", rentShophouse: "1.5k-3k" },
  "Bochum": { buyApt: "2.5k-4k", buyHouse: "400k-800k", buyLand: "200k-450k", buyShophouse: "600k-1.2M", rentApt: "8-12", rentHouse: "1.2k-2.5k", rentLand: "400-900", rentShophouse: "1.8k-3.5k" },
  "Wuppertal": { buyApt: "2.2k-3.8k", buyHouse: "350k-700k", buyLand: "180k-400k", buyShophouse: "550k-1.1M", rentApt: "7-11", rentHouse: "1.1k-2.2k", rentLand: "350-800", rentShophouse: "1.6k-3.2k" },
  "Bielefeld": { buyApt: "2.8k-4.5k", buyHouse: "500k-900k", buyLand: "250k-500k", buyShophouse: "750k-1.5M", rentApt: "9-13", rentHouse: "1.5k-2.8k", rentLand: "500-1k", rentShophouse: "2k-4k" },
  "Bonn": { buyApt: "4k-6k", buyHouse: "700k-1.5M", buyLand: "350k-800k", buyShophouse: "1M-2.2M", rentApt: "12-18", rentHouse: "1.8k-3.5k", rentLand: "700-1.5k", rentShophouse: "2.5k-5k" },
  "Münster": { buyApt: "4.5k-6.5k", buyHouse: "800k-1.6M", buyLand: "400k-900k", buyShophouse: "1.2M-2.5M", rentApt: "13-19", rentHouse: "2k-4k", rentLand: "800-1.8k", rentShophouse: "3k-6k" },
  "Karlsruhe": { buyApt: "4.5k-6.5k", buyHouse: "800k-1.6M", buyLand: "400k-900k", buyShophouse: "1.2M-2.5M", rentApt: "13-19", rentHouse: "2k-4k", rentLand: "800-1.8k", rentShophouse: "3k-6k" },
  "Mannheim": { buyApt: "3.5k-5.5k", buyHouse: "600k-1.2M", buyLand: "300k-650k", buyShophouse: "900k-1.8M", rentApt: "11-16", rentHouse: "1.5k-3k", rentLand: "500-1.2k", rentShophouse: "2.2k-4.5k" },
  "Augsburg": { buyApt: "4.5k-6.5k", buyHouse: "700k-1.4M", buyLand: "350k-750k", buyShophouse: "1M-2.2M", rentApt: "12-18", rentHouse: "1.8k-3.5k", rentLand: "700-1.5k", rentShophouse: "2.5k-5k" },
  "Wiesbaden": { buyApt: "4.5k-7k", buyHouse: "800k-1.8M", buyLand: "400k-1M", buyShophouse: "1.2M-2.8M", rentApt: "13-20", rentHouse: "2k-4k", rentLand: "800-1.8k", rentShophouse: "3k-6k" },
  "Gelsenkirchen": { buyApt: "1.5k-3k", buyHouse: "250k-500k", buyLand: "100k-250k", buyShophouse: "350k-750k", rentApt: "6-9", rentHouse: "800-1.8k", rentLand: "250-600", rentShophouse: "1.2k-2.5k" },
  "Mönchengladbach": { buyApt: "2.2k-3.8k", buyHouse: "350k-700k", buyLand: "180k-400k", buyShophouse: "550k-1.1M", rentApt: "7-11", rentHouse: "1.1k-2.2k", rentLand: "350-800", rentShophouse: "1.6k-3.2k" },
  "Braunschweig": { buyApt: "3k-5k", buyHouse: "500k-1M", buyLand: "250k-550k", buyShophouse: "750k-1.5M", rentApt: "10-15", rentHouse: "1.5k-3k", rentLand: "500-1.2k", rentShophouse: "2k-4.5k" },
  "Chemnitz": { buyApt: "1.5k-3k", buyHouse: "250k-500k", buyLand: "100k-250k", buyShophouse: "350k-750k", rentApt: "5-9", rentHouse: "800-1.8k", rentLand: "250-600", rentShophouse: "1.2k-2.5k" },
  "Kiel": { buyApt: "3.5k-5.5k", buyHouse: "600k-1.2M", buyLand: "300k-650k", buyShophouse: "900k-1.8M", rentApt: "10-15", rentHouse: "1.5k-3k", rentLand: "500-1.2k", rentShophouse: "2.2k-4.5k" },
  "Aachen": { buyApt: "3k-5k", buyHouse: "500k-1M", buyLand: "250k-550k", buyShophouse: "750k-1.5M", rentApt: "10-15", rentHouse: "1.5k-3k", rentLand: "500-1.2k", rentShophouse: "2k-4.5k" },
  "Freiburg": { buyApt: "5k-7.5k", buyHouse: "900k-1.8M", buyLand: "450k-1M", buyShophouse: "1.4M-2.8M", rentApt: "14-20", rentHouse: "2k-3.5k", rentLand: "800-1.5k", rentShophouse: "3k-5.5k" },
  "Heidelberg": { buyApt: "5.5k-8k", buyHouse: "1M-2.2M", buyLand: "500k-1.2M", buyShophouse: "1.5M-3.5M", rentApt: "15-22", rentHouse: "2.2k-4k", rentLand: "900-1.8k", rentShophouse: "3.5k-6k" },
  "Potsdam": { buyApt: "4.5k-7k", buyHouse: "800k-1.8M", buyLand: "400k-1M", buyShophouse: "1.2M-2.8M", rentApt: "13-19", rentHouse: "2k-3.8k", rentLand: "800-1.8k", rentShophouse: "3k-6k" },
  "Mainz": { buyApt: "4k-6.5k", buyHouse: "700k-1.5M", buyLand: "350k-800k", buyShophouse: "1M-2.2M", rentApt: "12-18", rentHouse: "1.8k-3.5k", rentLand: "700-1.5k", rentShophouse: "2.5k-5k" },
  "Rostock": { buyApt: "3k-5k", buyHouse: "500k-1M", buyLand: "250k-550k", buyShophouse: "750k-1.5M", rentApt: "9-14", rentHouse: "1.5k-2.8k", rentLand: "500-1k", rentShophouse: "2k-4k" },
  "Erfurt": { buyApt: "2.5k-4.5k", buyHouse: "400k-800k", buyLand: "200k-450k", buyShophouse: "600k-1.2M", rentApt: "8-13", rentHouse: "1.2k-2.5k", rentLand: "400-900", rentShophouse: "1.8k-3.5k" },
  "Saarbrücken": { buyApt: "2k-3.8k", buyHouse: "300k-600k", buyLand: "150k-350k", buyShophouse: "450k-900k", rentApt: "7-11", rentHouse: "1k-2k", rentLand: "300-700", rentShophouse: "1.5k-3k" }
};

export const COORDINATES: Record<string, [number, number]> = {
  // VN Cities
  "Hà Nội": [21.0285, 105.8542],
  "Hồ Chí Minh": [10.7769, 106.7009],
  "Đà Nẵng": [16.0544, 108.2022],
  "Hội An": [15.8801, 108.3380],
  "Bình Dương": [10.9805, 106.6515],
  "Đồng Nai": [10.9575, 106.8427],
  "Quảng Ninh": [20.9599, 107.0425],
  "Hải Phòng": [20.8449, 106.6881],
  "Cần Thơ": [10.0333, 105.7833],
  "Nha Trang": [12.2388, 109.1967],
  "Vũng Tàu": [10.3460, 107.0843],
  "Huế": [16.4637, 107.5909],
  "Vinh": [18.6733, 105.6880],
  "Đà Lạt": [11.9404, 108.4583],
  "Bắc Ninh": [21.1861, 106.0763],
  "Thanh Hóa": [19.8066, 105.7768],
  "Hưng Yên": [20.9333, 106.0500],
  "Vĩnh Phúc": [21.3093, 105.6046],
  "Thái Nguyên": [21.5639, 105.8251],
  "Hải Dương": [20.9338, 106.3164],
  "Nam Định": [20.4200, 106.1683],
  "Thái Bình": [20.4463, 106.3364],
  "Hà Nam": [20.5453, 105.9122],
  "Ninh Bình": [20.2547, 105.9750],
  "Quy Nhơn": [13.7830, 109.2197],
  "Buôn Ma Thuột": [12.6667, 108.0500],
  "Phú Quốc": [10.2899, 103.9840],
  "Long An": [10.6953, 106.2433],
  "Tiền Giang": [10.4286, 106.3719],
  "Sapa": [22.3364, 103.8438],
  "Phan Thiết": [10.9289, 108.1021],

  // DE Cities
  "Berlin": [52.5200, 13.4050],
  "München": [48.1351, 11.5820],
  "Hamburg": [53.5511, 9.9937],
  "Frankfurt": [50.1109, 8.6821],
  "Köln": [50.9375, 6.9603],
  "Düsseldorf": [51.2277, 6.7735],
  "Leipzig": [51.3397, 12.3731],
  "Stuttgart": [48.7758, 9.1829],
  "Dortmund": [51.5136, 7.4653],
  "Essen": [51.4556, 7.0116],
  "Bremen": [53.0793, 8.8017],
  "Dresden": [51.0504, 13.7373],
  "Hannover": [52.3759, 9.7320],
  "Nürnberg": [49.4521, 11.0767],
  "Duisburg": [51.4344, 6.7623],
  "Bochum": [51.4818, 7.2162],
  "Wuppertal": [51.2562, 7.1508],
  "Bielefeld": [52.0302, 8.5325],
  "Bonn": [50.7374, 7.0982],
  "Münster": [51.9607, 7.6261],
  "Karlsruhe": [49.0069, 8.4037],
  "Mannheim": [49.4875, 8.4660],
  "Augsburg": [48.3705, 10.8978],
  "Wiesbaden": [50.0782, 8.2398],
  "Gelsenkirchen": [51.5177, 7.0857],
  "Mönchengladbach": [51.1854, 6.4417],
  "Braunschweig": [52.2689, 10.5268],
  "Chemnitz": [50.8278, 12.9214],
  "Kiel": [54.3233, 10.1227],
  "Aachen": [50.7753, 6.0839],
  "Freiburg": [47.9990, 7.8421],
  "Heidelberg": [49.3988, 8.6724],
  "Potsdam": [52.3906, 13.0645],
  "Mainz": [49.9929, 8.2473],
  "Rostock": [54.0924, 12.0991],
  "Erfurt": [50.9848, 11.0299],
  "Saarbrücken": [49.2326, 6.9995],

  // VN Districts (Approximate centers)
  "Đông Anh": [21.1356, 105.8364],
  "Thường Tín": [20.8715, 105.8576],
  "Cầu Giấy": [21.0333, 105.7833],
  "Nam Từ Liêm": [21.0133, 105.7633],
  "Quận 1": [10.7769, 106.7009],
  "Thủ Đức": [10.8494, 106.7725],
  "Hải Châu": [16.0667, 108.2167],
  "Sơn Trà": [16.0833, 108.2333],
  "Lộc Thọ": [12.2388, 109.1967],
  "Phường 1": [10.3460, 107.0843],
  "Vĩnh Ninh": [16.4637, 107.5909],
  "Hưng Bình": [18.6733, 105.6880],
  
  // DE Districts (Approximate)
  "Mitte": [52.5200, 13.4050],
  "Pankow": [52.5667, 13.4000],
  "Schwabing": [48.1670, 11.5860],
  "Altstadt": [48.1370, 11.5750],
  "Altona": [53.5483, 9.9358],
  "Innenstadt": [50.1109, 8.6821]
};

export const RSS_FEEDS: Record<Market, string[]> = {
  VN: [
    "https://vnexpress.net/rss/bat-dong-san.rss",
    "https://cafef.vn/bat-dong-san.rss",
    "https://thanhnien.vn/rss/bat-dong-san.rss"
  ],
  DE: [
    "https://www.spiegel.de/wirtschaft/index.rss",
    "https://www.faz.net/rss/aktuell/finanzen/meine-finanzen/mieten-und-wohnen/",
    "https://www.welt.de/feeds/section/finanzen/immobilien.rss"
  ]
};
